version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app
    ports:
      - "80:3000"
    restart: always
    environment:
      NODE_ENV: development
networks:
  app: